# This compose file contains recipes that are called from the GitHub
# Actions workflows. Host networking is used, because it simplifies
# the connectivity from the cockroach process back to the cdc-sink
# test rig.
#
# Note that the names of the services in this file must align with
# the integration matrix variable in workflows/tests.yaml, as well
# as the values passed to sinktest.IntegrationMain.
version: "3.9"
services:
  cockroachdb-v20.2:
    image: cockroachdb/cockroach:latest-v20.2
    network_mode: host
    command: start-single-node --insecure
  cockroachdb-v21.1:
    image: cockroachdb/cockroach:latest-v21.1
    network_mode: host
    command: start-single-node --insecure
  cockroachdb-v21.2:
    image: cockroachdb/cockroach:latest-v21.2
    network_mode: host
    command: start-single-node --insecure
  mysql-v8:
<<<<<<< HEAD
    image: mysql:8-debian
=======
    image: mysql:8.0
>>>>>>> 0f60576 (wip: MySQL logical replication support)
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: SoupOrSecret
      MYSQL_DATABASE: _cdc_sink
    command: |
      --default-authentication-plugin=mysql_native_password
      --gtid_mode=on
      --enforce_gtid_consistency=on
    ports:
      - "3306:3306"
  postgresql-v11:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
  postgresql-v12:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
  postgresql-v13:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
  postgresql-v14:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
