# Copyright 2023 The Cockroach Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# This compose file contains recipes that are called from the GitHub
# Actions workflows. Host networking is used, because it simplifies
# the connectivity from the cockroach process back to the cdc-sink
# test rig.
#
# Note that the names of the services in this file must align with
# the integration matrix variable in workflows/tests.yaml, as well
# as the values passed to sinktest.IntegrationMain.
version: "3.9"
services:
  # These define the tested source databases. The network_mode is host
  # so that outgoing changefeed network requests can connect to the test
  # server.
  cockroachdb-v20.2:
    image: cockroachdb/cockroach:latest-v20.2
    network_mode: host
    command: start-single-node --insecure --store type=mem,size=2G
  cockroachdb-v21.1:
    image: cockroachdb/cockroach:latest-v21.1
    network_mode: host
    command: start-single-node --insecure --store type=mem,size=2G
  cockroachdb-v21.2:
    image: cockroachdb/cockroach:latest-v21.2
    network_mode: host
    command: start-single-node --insecure --store type=mem,size=2G
  cockroachdb-v22.1:
    image: cockroachdb/cockroach:latest-v22.1
    network_mode: host
    command: start-single-node --insecure --store type=mem,size=2G
  cockroachdb-v22.2:
    image: cockroachdb/cockroach:latest-v22.2
    network_mode: host
    command: start-single-node --insecure --store type=mem,size=2G
  cockroachdb-v23.1:
    image: cockroachdb/cockroach:latest-v23.1
    network_mode: host
    command: start-single-node --insecure --store type=mem,size=2G
  cockroachdb-v23.2:
    image: cockroachdb/cockroach:latest-v23.2
    network_mode: host
    command: start-single-node --insecure --store type=mem,size=2G

  # These two services are used for testing split-mode operations. We
  # need to bypass the usual entry-point script because it has a check
  # to ensure that the process only listens on localhost and on the
  # default port.
  #
  # https://github.com/cockroachdb/cockroach/issues/84166
  source-cockroachdb-v23.2:
    image: cockroachdb/cockroach:latest-v23.2
    network_mode: host
    entrypoint: /cockroach/cockroach
    command: start-single-node --insecure --store type=mem,size=2G --listen-addr :5400 --http-addr :8081
  target-cockroachdb-v23.2:
    image: cockroachdb/cockroach:latest-v23.2
    network_mode: host
    entrypoint: /cockroach/cockroach
    command: start-single-node --insecure --store type=mem,size=2G --listen-addr :5401 --http-addr :8082

  mysql-v5.7:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: SoupOrSecret
      MYSQL_DATABASE: _cdc_sink
    command:
      --default-authentication-plugin=mysql_native_password
      --gtid-mode=on
      --enforce-gtid-consistency=on
      --binlog-row-image=full
      --server-id=1
      --log-bin=log-bin
    ports:
      - "3306:3306"
  mysql-v5.6:
    image: mysql:5.6
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: SoupOrSecret
      MYSQL_DATABASE: _cdc_sink
    command:
      --default-authentication-plugin=mysql_native_password
      --gtid-mode=on
      --enforce-gtid-consistency=on
      --server-id=1
      --log-bin=mysql-binlog
      --binlog-format=row
      --binlog-row-image=full
      --log-slave-updates=ON
    ports:
      - "3306:3306"
  mysql-v8:
    image: mysql:8-debian
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: SoupOrSecret
      MYSQL_DATABASE: _cdc_sink
    command:
      --default-authentication-plugin=mysql_native_password
      --gtid-mode=on
      --enforce-gtid-consistency=on
      --binlog-row-metadata=full
    ports:
      - "3306:3306"
  mysql-mariadb-v10:
    image: mariadb:10
    platform: linux/x86_64
    environment:
      MARIADB_ROOT_PASSWORD: SoupOrSecret
      MARIADB_DATABASE: _cdc_sink
    command:
      --log-bin
      --server_id=1
      --log-basename=master1
      --binlog-format=row
      --binlog-row-metadata=full
    ports:
      - "3306:3306"
  oracle-v18.4:
    # Use a private mirror of the image to speed up CI tests. The original is at
    # container-registry.oracle.com/database/express:18.4.0-xe
    image: ghcr.io/cockroachdb/cdc-sink/oracle-express:18.4.0-xe
    platform: linux/x86_64
    environment:
      ORACLE_PWD: SoupOrSecret
    ports:
      - "1521:1521"
      - "5500:5500"
  oracle-v21.3:
    # Use a private mirror of the image to speed up CI tests. The original is at
    # container-registry.oracle.com/database/express:21.3.0-xe
    build: ./oracle-nne
    platform: linux/x86_64
    environment:
      ORACLE_PWD: SoupOrSecret
    ports:
      - "1521:1521"
      - "5500:5500"
  postgresql-v11:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_connections=512
  postgresql-v12:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_connections=512
  postgresql-v13:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_connections=512
  postgresql-v14:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_connections=512
  postgresql-v15:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: SoupOrSecret
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_connections=512

