resources:
  - ../../base/cockroachdb/
  - workload.yaml
nameSuffix: -source
commonLabels:
  side: source
replicas:
  - name: cockroachdb
    count: 16
  - name: workload
    count: 1
# Patch an environment variable that feeds the --join flag.
replacements:
  - source:
      kind: Service
      name: cockroachdb
    targets:
      - select:
          kind: StatefulSet
          name: cockroachdb
        fieldPaths:
          - spec.template.spec.containers.[name=cockroachdb].env.[name=COCKROACH_SERVICE].value
  - source:
      kind: Service
      name: cockroachdb-public
    targets:
      - select:
          kind: Deployment
          name: workload
        fieldPaths:
          - spec.template.spec.containers.[name=workload].env.[name=COCKROACH_SERVICE].value
          - spec.template.spec.initContainers.[name=load-fixtures].env.[name=COCKROACH_SERVICE].value
