name: Markdown
permissions:
  contents: read
on:
  push:
    branches: [master]
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Markdown Linter
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"
