# This workflow creates a GitHUb Status object that summarizes the
# outcome of other workflows. This allows status objects to drive
# additional workflow automation (e.g. automatic merge queue).
#
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
# https://docs.github.com/en/rest/commits/statuses
#
name: Status
permissions:
  statuses: write
on:
  workflow_run:
    workflows:
      - Binaries
      - Docker
      - Golang
    types:
      - completed
      - requested
env:
  STATUS_PREFIX: "Workflow"
jobs:
  status:
    name: Create Status Object
    runs-on: ubuntu-latest
    steps:
      - name: Determine state
        run: |
          if [ "${{ github.event.workflow_run.status }}" = "requested" ]
          then
            STATE="pending"
          else
            STATE="${{ github.event.workflow_run.conclusion }}"
          fi
          
          if [ -z "$STATE" ]
          then
            echo "Empty state"
            exit 1
          fi
          
          echo "STATE=$STATE" >> $GITHUB_ENV

      - name: Create status object
        run: |
          curl --request POST \
          --fail \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ env.STATE }}",
            "context": "${{ env.STATUS_PREFIX }} ${{ github.event.workflow.name }}",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }'
