name: Tests
permissions: read-all
on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
  workflow_dispatch: # Allow manual runs to kick off benchmarks
    inputs:
      run_bench:
        description: Run benchmarks
        required: false
        type: boolean

env:
  GO_VERSION: 1.17

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Determine paths to cache
        id: cache
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.cache.outputs.go-build }}
            ${{ steps.cache.outputs.go-mod }}
          key: ${{ runner.os }}-quality-${{ hashFiles('**/go.sum') }}

      # This action should, in general, be a no-op, given the cache above.
      - name: Download all deps
        run: go mod download

      - name: crlfmt returns no deltas
        if: ${{ always() }}
        run: |
          DELTA=$(go run github.com/cockroachdb/crlfmt -ignore _gen.go .)
          echo $DELTA
          test -z "$DELTA"

      - name: Lint
        if: ${{ always() }}
        run: go run golang.org/x/lint/golint -set_exit_status ./...

      - name: Static checks
        if: ${{ always() }}
        run: go run honnef.co/go/tools/cmd/staticcheck -checks all ./...

  integration:
    name: Integration Tests crdb-${{ matrix.cockroachdb }} ${{ matrix.integration }}
    strategy:
      fail-fast: false
      matrix:
        cockroachdb: [ v20.2, v21.1, v21.2, v22.1 ]
        # This matrix component should use the target names listed
        # in the docker-compose.yml file in the parent directory.
        integration:
          - "mysql-v8"
          - "mysql-mariadb-v10"
          - "postgresql-v11"
          - "postgresql-v12"
          - "postgresql-v13"
          - "postgresql-v14"
    runs-on: ubuntu-latest
    env:
      COVER_OUT: coverage.out
      JUNIT_OUT: junit-${{ matrix.cockroachdb }}-${{ matrix.integration }}.xml
      TEST_OUT: go-test-${{ matrix.cockroachdb }}-${{ matrix.integration }}.json
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Determine paths to cache
        id: cache
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.cache.outputs.go-build }}
            ${{ steps.cache.outputs.go-mod }}
          key: ${{ runner.os }}-integration-${{ hashFiles('**/go.sum') }}

      # This action should, in general, be a no-op, given the cache above.
      - name: Download all deps
        run: go mod download

      - name: Start CockroachDB
        working-directory: .github
        run: docker-compose up -d cockroachdb-${{ matrix.cockroachdb }}

      - name: Start ${{ matrix.integration }}
        if: ${{ matrix.integration }}
        working-directory: .github
        run: docker-compose up -d ${{ matrix.integration }}

      # The go test json output will be written into a file that's
      # processed by a subsequent step into a JUnit.xml file. The test
      # reports are aggregated later on to produce a nicer summary of
      # the test output in the GitHub Actions UI.
      #
      # Inspired by
      # https://www.cloudwithchris.com/blog/githubactions-testsummary-go/
      - name: Go Tests
        env:
          COCKROACH_DEV_LICENSE: ${{ secrets.COCKROACH_DEV_LICENSE }}
          CDC_INTEGRATION: ${{ matrix.integration }}
        run: >
          go test
          -coverpkg=./internal/...
          -covermode=atomic
          -coverprofile=${{ env.COVER_OUT }}
          -json
          -race
          ./... > ${{ env.TEST_OUT }}

      - name: Manual Benchmarks
        if: ${{ github.event.inputs.run_bench }}
        env:
          COCKROACH_DEV_LICENSE: ${{ secrets.COCKROACH_DEV_LICENSE }}
          CDC_INTEGRATION: ${{ matrix.integration }}
        run: go test -v -benchtime 10s -bench . ./...

      - name: Stop databases
        if: ${{ always() }}
        working-directory: .github
        run: docker-compose down

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.COVER_OUT }}

      - name: Convert test json to JUnit xml
        if: always()
        run: >
          go run github.com/jstemmer/go-junit-report/v2
          -parser gojson
          -in ${{ env.TEST_OUT }}
          -out ${{ env.JUNIT_OUT }}
          -p cockroachdb=${{ matrix.cockroachdb }}
          -p integration=${{ matrix.integration }}
          -package-name ${{ matrix.cockroachdb }}-${{ matrix.integration }}

      # Upload all test reports to a common artifact name, to make them
      # available to the summarization step. The go test json is
      # uploaded as a developer convenience.
      - name: Stash test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: integration-reports
          path: |
            ${{ env.JUNIT_OUT }}
            ${{ env.TEST_OUT }}
          retention-days: 7

  # This job downloads the JUnit.xml files generated in the integration
  # job and summarizes them into the GitHub Actions UI.
  summarize:
    name: Test summaries
    runs-on: ubuntu-latest
    needs: integration
    if: always()
    steps:
      - name: Download reports
        uses: actions/download-artifact@v3
        with:
          name: integration-reports
      - name: Summarize
        uses: test-summary/action@v1
        with:
          paths: junit-*.xml